<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>KeePassSync</RootNamespace>
    <AssemblyName>KeePassSync</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="KeePass">
      <HintPath>C:\Program Files\KeePass Password Safe 2\KeePass.exe</HintPath>
    </Reference>
    
    <Reference Include="System" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
